/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: BlackSpire (https://sketchfab.com/blackspire)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/jack-trigger-0d251b65dfa04e3e88cd8774b77c3a27
title: Jack Trigger
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import '../public/'
export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={0.01}>
            <mesh geometry={nodes.Smoke_mat.geometry} material={materials.Smoke_mat} />
            <mesh geometry={nodes.Smoke_mat_1.geometry} material={materials.Smoke_mat} />
            <mesh geometry={nodes.Smoke_mat_2.geometry} material={materials.Smoke_mat} />
            <mesh geometry={nodes.R_Shoulder_Armor_mat.geometry} material={materials.R_Shoulder_Armor_mat} />
            <mesh geometry={nodes.R_Shoulder_Armor_mat_1.geometry} material={materials.R_Shoulder_Armor_mat} />
            <mesh geometry={nodes.R_Shoulder_Armor_mat_2.geometry} material={materials.R_Shoulder_Armor_mat} />
            <mesh geometry={nodes.R_Shoulder_Armor_mat_3.geometry} material={materials.R_Shoulder_Armor_mat} />
            <mesh geometry={nodes.R_Shoulder_Armor_mat_4.geometry} material={materials.R_Shoulder_Armor_mat} />
            <mesh geometry={nodes.R_Leg_mat.geometry} material={materials.R_Leg_mat} />
            <mesh geometry={nodes.R_Leg_mat_1.geometry} material={materials.R_Leg_mat} />
            <mesh geometry={nodes.R_Leg_mat_2.geometry} material={materials.R_Leg_mat} />
            <mesh geometry={nodes.R_Leg_mat_3.geometry} material={materials.R_Leg_mat} />
            <mesh geometry={nodes.R_Leg_mat_4.geometry} material={materials.R_Leg_mat} />
            <mesh geometry={nodes.R_Leg_mat_5.geometry} material={materials.R_Leg_mat} />
            <mesh geometry={nodes.R_Arm_mat.geometry} material={materials.R_Arm_mat} />
            <mesh geometry={nodes.R_Arm_mat_1.geometry} material={materials.R_Arm_mat} />
            <mesh geometry={nodes.R_Arm_mat_2.geometry} material={materials.R_Arm_mat} />
            <mesh geometry={nodes.R_Arm_mat_3.geometry} material={materials.R_Arm_mat} />
            <mesh geometry={nodes.L_Shoulder_Armor_mat.geometry} material={materials.L_Shoulder_Armor_mat} />
            <mesh geometry={nodes.L_Shoulder_Armor_mat_1.geometry} material={materials.L_Shoulder_Armor_mat} />
            <mesh geometry={nodes.L_Shoulder_Armor_mat_2.geometry} material={materials.L_Shoulder_Armor_mat} />
            <mesh geometry={nodes.L_Leg_mat.geometry} material={materials.L_Leg_mat} />
            <mesh geometry={nodes.L_Leg_mat_1.geometry} material={materials.L_Leg_mat} />
            <mesh geometry={nodes.L_Leg_mat_2.geometry} material={materials.L_Leg_mat} />
            <mesh geometry={nodes.L_Leg_mat_3.geometry} material={materials.L_Leg_mat} />
            <mesh geometry={nodes.L_Arm_mat.geometry} material={materials.L_Arm_mat} />
            <mesh geometry={nodes.L_Arm_mat_1.geometry} material={materials.L_Arm_mat} />
            <mesh geometry={nodes.L_Arm_mat_2.geometry} material={materials.L_Arm_mat} />
            <mesh geometry={nodes.L_Arm_mat_3.geometry} material={materials.L_Arm_mat} />
            <mesh geometry={nodes.L_Arm_mat_4.geometry} material={materials.L_Arm_mat} />
            <mesh geometry={nodes.L_Arm_mat_5.geometry} material={materials.L_Arm_mat} />
            <mesh geometry={nodes.L_Arm_mat_6.geometry} material={materials.L_Arm_mat} />
            <mesh geometry={nodes.L_Arm_mat_7.geometry} material={materials.L_Arm_mat} />
            <mesh geometry={nodes.L_Arm_mat_8.geometry} material={materials.L_Arm_mat} />
            <mesh geometry={nodes.L_Arm_mat_9.geometry} material={materials.L_Arm_mat} />
            <mesh geometry={nodes.L_Arm_mat_10.geometry} material={materials.L_Arm_mat} />
            <mesh geometry={nodes.Head_mat.geometry} material={materials.Head_mat} />
            <mesh geometry={nodes.Body_mat.geometry} material={materials.Body_mat} />
            <mesh geometry={nodes.Body_mat_1.geometry} material={materials.Body_mat} />
            <mesh geometry={nodes.Body_mat_2.geometry} material={materials.Body_mat} />
            <mesh geometry={nodes.Body_mat_3.geometry} material={materials.Body_mat} />
            <mesh geometry={nodes.Body_mat_4.geometry} material={materials.Body_mat} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model.gltf')
